### ISSUE TITLE
Characters like p, q, j, g are cut at the bottom in code and command examples

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkusio.github.io#110]
Characters like p, q, j, g are cut at the bottom in code and command examples.

<img width="540" alt="screenshot 2019-03-07 at 10 40 53" src="https://user-images.githubusercontent.com/925259/53947817-d0112e80-40c6-11e9-9346-1069ff9510ca.png">
<img width="540" alt="screenshot 2019-03-07 at 10 41 11" src="https://user-images.githubusercontent.com/925259/53947818-d0112e80-40c6-11e9-9a01-19ee3b72ca89.png">

I tried to fix it via https://github.com/rsvoboda/quarkusio.github.io/commit/b4e22b1ef2feb44e12989ac07ffae5c42e9e564e but it has side effects :(

**Comment by gekorob** [comment]
Hi all,
  is it possible to add a *line-height: 1.4;* to the *.hljs* class?

```scss
.hljs {
  display: inline;
  overflow: inherit;
  overflow-x: inherit;
  overflow-y: hidden;
  background: inherit;
  padding: 0;
  line-height: 1.4;
}
``` 
in the *quarkus.scss* ?

This shoud fix the problem for the highlights section.
