### ISSUE TITLE
Add `:target` highlight for Configuration reference table

### ISSUE THREAD

**Issue by rgmz** [quarkusio/quarkusio.github.io#2332]
When linking to a specific configuration property (e.g., https://quarkus.io/guides/logging#quarkus-logging-json_quarkus-log-console-json-key-overrides), it's not always obvious which element was linked without checking the URL hash. It would be a nice UX improvement if the selected element had a distinct highlight.

Something like below, except less horrible:
```css
td:has(a:target) {
  background-color: yellow;
}
```
